{% set name = "displayhooks" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/displayhooks-{{ version }}.tar.gz
  sha256: bd72d833b2fd7eba5c5a5b05d486f8519f0e35ee573a759755f84697a81938d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - displayhooks
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/displayhooks
  summary: Extend the capabilities of the standard displayhook in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
